// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SaveFileMetadata } from "./SaveFileMetadata";

export type GameConfig = {
  gameName: string;
  saveFolderPath: string;
  maxSaveBackups: number;
  saveFiles: Array<SaveFileMetadata>;
  watcherEnabled: boolean;
};
