// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameConfig } from "./GameConfig";

export type ProgramConfig = { games: { [key: string]: GameConfig }; configVersion: number };
